// Generated by scripts/generate-mastery-kits.mjs. Do not edit by hand.
// Uses only Node.js built-ins and never reads a reference solution directory.

import test from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const candidateRoot = existsSync(join(projectRoot, "starter"))
  ? join(projectRoot, "starter")
  : projectRoot;
const read = (path) => readFileSync(join(candidateRoot, path), "utf8");

const css = read("styles.css");
const withoutComments = css.replace(/\/\*[\s\S]*?\*\//g, "");
const rule = (selector) => {
  const escaped = selector.replace(/[.*+?^\${}()|[\]\\]/g, "\\$&");
  return withoutComments.match(new RegExp(escaped + "\\s*{([^}]*)}", "i"))?.[1] ?? "";
};

test("defines purpose-named design tokens and a flexible form", () => {
  const root = rule(":root");
  const tokens = [...root.matchAll(/--([a-z0-9-]+)\s*:/gi)].map((match) => match[1]);
  assert.ok(tokens.length >= 10, "define a useful token set");
  for (const purpose of ["page", "surface", "text", "border", "accent", "focus", "space"]) {
    assert.ok(tokens.some((token) => token.includes(purpose)), "missing a " + purpose + " token");
  }
  assert.match(rule(".signup-card"), /\bwidth\s*:\s*min\(/i);
});

test("styles controls and every required interaction state", () => {
  assert.match(withoutComments, /input\s*,\s*select\s*,\s*button\s*{[^}]*min-height\s*:[^;}]+;?[^}]*font\s*:\s*inherit/si);
  assert.ok(/button:hover\s*{[^}]+}/si.test(withoutComments));
  assert.match(withoutComments, /:focus-visible\s*{[^}]*outline\s*:\s*(?!none)/si);
  assert.ok(/:user-invalid\s*{[^}]+}/si.test(withoutComments));
  assert.ok(/:disabled\s*{[^}]+}/si.test(withoutComments));
});

test("responds to dark color and reduced-motion preferences", () => {
  const dark = withoutComments.match(/@media\s*\(prefers-color-scheme\s*:\s*dark\)\s*{([\s\S]*?)\n}/i)?.[1] ?? "";
  assert.ok((dark.match(/--[a-z0-9-]+\s*:/gi) ?? []).length >= 6, "override semantic colors in dark mode");
  const reduced = withoutComments.match(/@media\s*\(prefers-reduced-motion\s*:\s*reduce\)\s*{([\s\S]*?)\n}/i)?.[1] ?? "";
  assert.match(reduced, /(?:transition|animation)(?:-duration)?\s*:/i);
});
